"use client";

import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";

type EthereumProvider = { request: (args: { method: string; params?: unknown[] }) => Promise<unknown> };
type ProviderError = { code?: number | string; message?: string; data?: unknown };
type PaymentRequest = { id: string; payeeName: string; recipient: string; amount: string; purpose: string };
type Receipt = PaymentRequest & { payer: string; txHash: string; finalizedAt: string };
declare global { interface Window { ethereum?: EthereumProvider } }

// Arc Testnet is chain 5042002 (0x4cef52). This value must match the wallet's chain ID exactly.
const ARC_CHAIN_ID = "0x4cef52";
const ARC_RPC = "https://rpc.testnet.arc.network";
const ARC_EXPLORER = "https://testnet.arcscan.app";
const USDC_DECIMALS = 18;
const MAX_AUTO_APPROVAL_USDC = 25;
const ARC_MIN_MAX_FEE_PER_GAS = 20_000_000_000n; // 20 Gwei Arc Testnet fee floor
const ARC_PRIORITY_FEE_PER_GAS = 1_000_000_000n; // 1 Gwei suggested Arc tip

function shortAddress(value: string) { return value ? `${value.slice(0, 6)}...${value.slice(-4)}` : "Not connected"; }
function toBaseUnits(amount: string) { const [whole, fraction = ""] = amount.trim().split("."); const padded = `${fraction.replace(/\D/g, "").slice(0, USDC_DECIMALS)}${"0".repeat(USDC_DECIMALS)}`.slice(0, USDC_DECIMALS); return `0x${(BigInt(whole || "0") * 10n ** BigInt(USDC_DECIMALS) + BigInt(padded || "0")).toString(16)}`; }
function fromBaseUnits(value: string) { const amount = BigInt(value); const whole = amount / 10n ** BigInt(USDC_DECIMALS); const fraction = (amount % 10n ** BigInt(USDC_DECIMALS)).toString().padStart(USDC_DECIMALS, "0").slice(0, 2); return `${whole}.${fraction}`; }
function loadRequestFromUrl(): PaymentRequest | null { if (typeof window === "undefined") return null; const params = new URLSearchParams(window.location.search); const recipient = params.get("to"); const amount = params.get("amount"); if (!recipient || !amount) return null; return { id: params.get("id") || crypto.randomUUID(), payeeName: params.get("payee") || "ArcFlow recipient", recipient, amount, purpose: params.get("purpose") || "ArcFlow payment request" }; }
function isValidRecipient(value: string) { return /^0x[a-fA-F0-9]{40}$/.test(value) && !/^0x0{40}$/i.test(value); }
function isValidAmount(value: string) { return /^\d+(?:\.\d{1,18})?$/.test(value.trim()) && Number(value) > 0; }
function formatProviderError(error: unknown, fallback: string) { const providerError = error as ProviderError; const message = providerError?.message || (typeof providerError?.data === "object" && providerError.data && "message" in providerError.data ? String((providerError.data as { message?: unknown }).message || "") : "") || fallback; const code = providerError?.code; return code === undefined ? message : `${message} (wallet error ${code})`; }
function wasRejected(error: unknown) { const providerError = error as ProviderError; return providerError?.code === 4001 || /rejected|denied|cancelled/i.test(providerError?.message || ""); }

export default function Home() {
  const [account, setAccount] = useState(""); const [balance, setBalance] = useState(""); const [networkReady, setNetworkReady] = useState(false); const [status, setStatus] = useState("Connect a browser wallet to begin."); const [request, setRequest] = useState<PaymentRequest | null>(null); const [receipt, setReceipt] = useState<Receipt | null>(null); const [shareUrl, setShareUrl] = useState(""); const [form, setForm] = useState({ payeeName: "", recipient: "", amount: "5.00", purpose: "" });
  const decision = useMemo(() => { if (!request) return null; const amount = Number(request.amount); const available = Number(balance || 0); const enoughBalance = !balance || available >= amount; return { approved: amount > 0 && amount <= MAX_AUTO_APPROVAL_USDC && enoughBalance, reason: amount > MAX_AUTO_APPROVAL_USDC ? `Needs extra review because it exceeds the ${MAX_AUTO_APPROVAL_USDC} USDC policy limit.` : !enoughBalance ? "Insufficient visible native USDC balance for this payment." : "Within the configured payment policy and ready for explicit user approval." }; }, [balance, request]);
  useEffect(() => { const incomingRequest = loadRequestFromUrl(); if (incomingRequest) setRequest(incomingRequest); }, []);
  async function verifyArcChain() { if (!window.ethereum) throw new Error("No browser wallet found. Install MetaMask or another EIP-1193 wallet."); const chainId = await window.ethereum.request({ method: "eth_chainId" }); const onArc = typeof chainId === "string" && chainId.toLowerCase() === ARC_CHAIN_ID; setNetworkReady(onArc); if (!onArc) throw new Error(`Wrong network: switch MetaMask to Arc Testnet (chain 5042002) before approving.`); }
  async function switchToArc() { if (!window.ethereum) throw new Error("No browser wallet found. Install MetaMask or another EIP-1193 wallet."); try { await window.ethereum.request({ method: "wallet_switchEthereumChain", params: [{ chainId: ARC_CHAIN_ID }] }); } catch (error) { const code = (error as ProviderError).code; if (code !== 4902) throw error; await window.ethereum.request({ method: "wallet_addEthereumChain", params: [{ chainId: ARC_CHAIN_ID, chainName: "Arc Testnet", nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 }, rpcUrls: [ARC_RPC], blockExplorerUrls: [ARC_EXPLORER] }] }); } await verifyArcChain(); }
  async function refreshBalance(address = account) { if (!window.ethereum || !address) return; const raw = await window.ethereum.request({ method: "eth_getBalance", params: [address, "latest"] }) as string; setBalance(fromBaseUnits(raw)); }
  async function connectWallet() { try { if (!window.ethereum) throw new Error("No browser wallet found. Install MetaMask or another EIP-1193 wallet."); setStatus("Requesting wallet connection..."); const accounts = await window.ethereum.request({ method: "eth_requestAccounts" }) as string[]; const connected = accounts[0] || ""; if (!connected) throw new Error("No wallet account was returned."); setAccount(connected); await switchToArc(); await refreshBalance(connected); setStatus("Wallet connected to Arc Testnet. Native USDC covers payment and gas."); } catch (error) { setStatus(formatProviderError(error, "Could not connect wallet.")); } }
  function createRequest(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!isValidRecipient(form.recipient)) { setStatus("Enter a valid, non-zero 0x recipient address."); return; } if (!isValidAmount(form.amount)) { setStatus("Enter a payment amount greater than zero with up to 18 decimals."); return; } const nextRequest: PaymentRequest = { id: crypto.randomUUID(), ...form }; setRequest(nextRequest); const url = new URL(window.location.href); url.search = new URLSearchParams({ id: nextRequest.id, payee: nextRequest.payeeName, to: nextRequest.recipient, amount: nextRequest.amount, purpose: nextRequest.purpose }).toString(); setShareUrl(url.toString()); setStatus("Payment request created. Copy the link or pay it from this wallet."); }
  async function arcFeeFallback() { let suggestedFee = ARC_MIN_MAX_FEE_PER_GAS; try { const gasPrice = await window.ethereum?.request({ method: "eth_gasPrice" }); if (typeof gasPrice === "string") suggestedFee = BigInt(gasPrice); } catch { /* The Arc minimum below remains safe when fee lookup is unavailable. */ } const maxFee = (suggestedFee > ARC_MIN_MAX_FEE_PER_GAS ? suggestedFee : ARC_MIN_MAX_FEE_PER_GAS) + ARC_PRIORITY_FEE_PER_GAS; return { maxFeePerGas: `0x${maxFee.toString(16)}`, maxPriorityFeePerGas: `0x${ARC_PRIORITY_FEE_PER_GAS.toString(16)}` }; }
  async function payRequest() { if (!request || !account || !window.ethereum) return; if (!decision?.approved) { setStatus(decision?.reason || "Payment cannot be approved."); return; } if (!isValidRecipient(request.recipient)) { setStatus("Payment blocked: the request has an invalid or zero recipient address."); return; } if (!isValidAmount(request.amount)) { setStatus("Payment blocked: the request amount is invalid."); return; } try { if (!networkReady) { setStatus("Switching to Arc Testnet..."); await switchToArc(); } await verifyArcChain(); const activeAccounts = await window.ethereum.request({ method: "eth_accounts" }) as string[]; if (!activeAccounts.some((address) => address.toLowerCase() === account.toLowerCase())) throw new Error("The connected account is no longer available in MetaMask. Connect the wallet again."); const basicTransaction = { from: account, to: request.recipient, value: toBaseUnits(request.amount) }; setStatus("Confirm the native USDC payment in MetaMask..."); let txHash: string; try { txHash = await window.ethereum.request({ method: "eth_sendTransaction", params: [basicTransaction] }) as string; } catch (basicError) { if (wasRejected(basicError)) throw basicError; setStatus("Basic transaction request was not accepted. Retrying with Arc-compatible fee settings..."); const fees = await arcFeeFallback(); txHash = await window.ethereum.request({ method: "eth_sendTransaction", params: [{ ...basicTransaction, ...fees }] }) as string; } setStatus("Payment submitted. Waiting for Arc finality..."); for (let attempt = 0; attempt < 30; attempt += 1) { const txReceipt = await window.ethereum.request({ method: "eth_getTransactionReceipt", params: [txHash] }) as { status?: string } | null; if (txReceipt?.status === "0x1") { const nextReceipt = { ...request, payer: account, txHash, finalizedAt: new Date().toISOString() }; setReceipt(nextReceipt); localStorage.setItem(`arcflow-receipt-${request.id}`, JSON.stringify(nextReceipt)); setStatus("Payment final on Arc. Your receipt is ready to verify on ArcScan."); await refreshBalance(); return; } if (txReceipt?.status === "0x0") throw new Error("The payment transaction reverted."); await new Promise((resolve) => window.setTimeout(resolve, 1000)); } throw new Error("Timed out while waiting for the payment receipt."); } catch (error) { setStatus(formatProviderError(error, "Payment could not be completed.")); } }

  return <main className="app-frame min-h-screen px-4 py-5 sm:px-6 md:px-10 md:py-8"><section className="shell mx-auto">
    <header className="site-header"><div className="brand-lockup"><ArcMark/><div><p className="eyebrow mb-1">Stablecoin payment desk</p><h1>Arc<span>Flow</span></h1></div></div><div className="header-actions"><span className="network-note">Built on Arc Testnet <em>· independent project</em></span><button onClick={connectWallet} className="wallet-button px-4">{account ? `Connected: ${shortAddress(account)}` : "Connect wallet"}</button></div></header>
    <div className="overview"><section className="surface intro-surface"><div className="intro-copy"><p className="eyebrow">A clear settlement record</p><h2>Move USDC with a decision trail your team can trust.</h2><p>Create a clear payment request, review the policy outcome, then approve the transaction in your own wallet. No funds move without your signature.</p></div><div className="workflow" aria-label="Payment workflow"><Milestone number="1" label="Request" active/><span className="connector"/><Milestone number="2" label="Review" active={Boolean(request)}/><span className="connector"/><Milestone number="3" label="Approve" active={Boolean(receipt)}/></div></section><Metric label="Network" value={networkReady ? "Arc Testnet" : "Wallet required"} detail="Chain ID 5042002"/><Metric label="Available balance" value={balance ? `${balance} USDC` : "--"} detail="Native USDC funds gas"/></div>
    <div className="status" role="status" aria-live="polite"><span className="status-dot" aria-hidden="true"/>{status}</div>
    <div className="workbench"><section className="surface compose-panel"><div className="section-heading"><div><p className="eyebrow">01 - Compose</p><h2>Create a payment request</h2></div><span className="currency-pill">USDC</span></div><form onSubmit={createRequest} className="space-y-4"><Field label="Payee name"><input className="field-control" required value={form.payeeName} onChange={(event) => setForm({ ...form, payeeName: event.target.value })} placeholder="Maya Design Studio"/></Field><Field label="Recipient address"><input className="field-control font-mono text-sm" required value={form.recipient} onChange={(event) => setForm({ ...form, recipient: event.target.value })} placeholder="0x..."/></Field><div className="grid gap-4 sm:grid-cols-[.8fr_1.2fr]"><Field label="Amount"><div className="relative"><input className="field-control pr-16" required inputMode="decimal" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} placeholder="5.00"/><span className="currency-code">USDC</span></div></Field><Field label="Purpose"><input className="field-control" required value={form.purpose} onChange={(event) => setForm({ ...form, purpose: event.target.value })} placeholder="Design milestone 01"/></Field></div><button className="primary-button w-full px-5">Create payment request</button><p className="form-note">A shareable request includes the recipient, amount, and purpose for a transparent review.</p></form>{shareUrl && <div className="share-link"><p>Shareable payment link</p><p className="break-all font-mono">{shareUrl}</p></div>}</section>
      <section className="surface review-panel"><div className="section-heading"><div><p className="eyebrow">02 - Review and approve</p><h2>Payment decision</h2></div></div>{!request ? <EmptyState/> : <PaymentCard request={request} decision={decision} receipt={receipt} onPay={payRequest} account={account}/>}</section></div>
    <section className="assurance-notes"><Info title="Native USDC rail" copy="The connected wallet submits a native USDC transfer on Arc Testnet. USDC also covers gas."/><Info title="Approval remains yours" copy="Policy checks inform the decision. Your wallet signature is still required for every payment."/><Info title="Proof after finality" copy="A successful onchain receipt is saved locally and can be independently checked on ArcScan."/></section>
    <footer className="app-footer"><span>Independent interface for Arc Testnet</span><span>Arc-inspired mark, not an official Arc logo</span></footer>
  </section></main>;
}

function ArcMark() { return <div className="brand-mark" aria-hidden="true"><svg viewBox="0 0 42 42" fill="none"><path d="M8.5 27.8c2.4-8.9 8-14.1 16.6-14.1 3.1 0 5.9.7 8.4 2" stroke="currentColor" strokeWidth="3.3" strokeLinecap="round"/><path d="M11.2 32.5c3.3-5.3 8-8 14.1-8 2.9 0 5.5.6 7.7 1.9" stroke="currentColor" strokeWidth="3.3" strokeLinecap="round"/><circle cx="32.5" cy="15.7" r="2.5" fill="currentColor"/></svg></div>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="metric"><p>{label}</p><strong>{value}</strong><span>{detail}</span></div>; }
function Milestone({ number, label, active = false }: { number: string; label: string; active?: boolean }) { return <span className={`milestone ${active ? "active" : ""}`}><i>{number}</i><span>{label}</span></span>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="field-label">{label}</span>{children}</label>; }
function EmptyState() { return <div className="empty-state"><div className="empty-symbol" aria-hidden="true">+</div><p>A considered payment starts here</p><span>Create a request or open a shared link to see the amount, recipient, policy outcome, and explicit approval step in one place.</span><div>Approval-first workflow</div></div>; }
function PaymentCard({ request, decision, receipt, onPay, account }: { request: PaymentRequest; decision: { approved: boolean; reason: string } | null; receipt: Receipt | null; onPay: () => void; account: string }) { if (receipt) return <div className="receipt-card"><p className="eyebrow">Payment final</p><h2>{receipt.amount} USDC sent</h2><p>{receipt.purpose}</p><div className="receipt-details"><ReceiptRow label="Payer" value={shortAddress(receipt.payer)}/><ReceiptRow label="Recipient" value={shortAddress(receipt.recipient)}/><ReceiptRow label="Finalized" value={new Date(receipt.finalizedAt).toLocaleString()}/></div><a className="primary-button mt-5 inline-flex items-center px-4" href={`${ARC_EXPLORER}/tx/${receipt.txHash}`} target="_blank" rel="noreferrer">Verify on ArcScan</a></div>; return <div className="space-y-5"><div className="request-summary"><p>Payment request</p><div><h2>{request.amount} <span>USDC</span></h2><span>To {request.payeeName}</span></div><p>{request.purpose}</p></div><div className="receipt-details"><ReceiptRow label="Recipient" value={shortAddress(request.recipient)}/><ReceiptRow label="Paying wallet" value={shortAddress(account)}/><ReceiptRow label="Network fee" value="Native USDC"/></div><div className={`decision ${decision?.approved ? "decision-approved" : "decision-review"}`}><p className="eyebrow">{decision?.approved ? "Ready for your approval" : "Review required"}</p><p>{decision?.reason}</p></div><button onClick={onPay} disabled={!decision?.approved || !account} className="approval-button w-full px-5">{!account ? "Connect wallet to approve" : decision?.approved ? `Approve ${request.amount} USDC` : "Approval unavailable"}</button></div>; }
function ReceiptRow({ label, value }: { label: string; value: string }) { return <div className="receipt-row"><span>{label}</span><strong>{value}</strong></div>; }
function Info({ title, copy }: { title: string; copy: string }) { return <article><div aria-hidden="true"/><h3>{title}</h3><p>{copy}</p></article>; }
